[package]
name = "rust-pipe"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
nom = "8.0.0"
nom-language = "0.1.0"
thiserror = "2.0.17"
clipboard-win = "5.4.1"
cmd-help = { path = "./cmd_help" }