# rustfmt.toml
max_width = 120
use_small_heuristics = "Max"

# 减少不必要的换行
imports_granularity = "Crate"
imports_layout = "Horizontal"

# 函数和方法链
fn_call_width = 120
chain_width = 120
fn_args_layout = "Compressed"

# 控制括号和空格
brace_style = "SameLineWhere"
empty_item_single_line = true
format_strings = true
merge_derives = true

# 结构体和枚举
struct_variant_width = 120
enum_discrim_align_threshold = 0

# 空格控制
#spaces_around_ranges = false
#binop_separator = "Front"